### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/qiwis#121]
I got to know [semantic versioning](https://semver.org) lately.

Let's follow this rule, for convenient dependency control.
@BECATRUE is it possible to change the released versions' names?

**Comment by BECATRUE** [comment]
Why is it an issue, not a discussion?
Should we change the version naming?

**Comment by BECATRUE** [comment]
> Is it possible to change the released versions' names?

Probably yes! I know that it is possible through just changing `tag` name.
