### ISSUE TITLE
Add the logo as icon and background

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/qiwis#165]
### Feature you want to implement
The logo will be drawn in `self.centralWidget`.

### How the feature is implemented
- The background image is stored in `resources/background.png`.
- The implementation is referred to the [artiq dashboard](https://github.com/m-labs/artiq/blob/master/artiq/frontend/artiq_dashboard.py#L82).

### Additional context
Thanks for designing this "QIWIS" logo. @choiwh03 

<image width="30%" src="https://github.com/snu-quiqcl/qiwis/assets/76851886/6fd55f62-3224-4327-928c-fb66fb548e0b">

**Comment by BECATRUE** [comment]
I have a question!
Which should I match the background image to, `mainWindow.centralWidget` or full application?

Please leave your opinion! @kangz12345

**Comment by kangz12345** [comment]
What are the differences for those two options?

**Comment by BECATRUE** [comment]
Fisrt, matching `mainWindow.centralWidget` means filling the remainder region out of dock widgets as follows.

![image](https://github.com/snu-quiqcl/swift/assets/76851886/9ba22833-1128-4b7c-a11f-10e3c541b833)

Second, matching the full application means filling the `qapp` as follows.

![image](https://github.com/snu-quiqcl/swift/assets/76851886/c7abb029-e410-4688-8df7-b86f52de9a61)

As I didn't implement all, there are some weird parts so please understand this..

**Comment by kangz12345** [comment]
Oh thank you for the visual support!! It looks great, I think matching the full app yet with the smaller image would be good!
