### ISSUE TITLE
Resolve an import error in pip installation

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/qiwis#175]
I tried to resolve the Pylint action bug in [iquip](https://github.com/snu-quiqcl/iquip) project.
While looking for a solution, I found out the followings:
- Using `pip install -e` in the GitHub action may not work well.
- We have to use only `pip install`.
So we need to update the release using `pip install`, not `-e` option.

In the current status, however, `pip install ${url}` causes an error as follows:
<img width="40%" src="https://github.com/snu-quiqcl/qiwis/assets/76851886/d524e31e-1763-499f-b09e-8fedbc7ce7b9">

Thus, I will resolve this error and make `pip install` available.

**Comment by BECATRUE** [comment]
Oh, I didn't release the fixed version yet, so I reopen this.

**Comment by BECATRUE** [comment]
Please check the relaeae draft and if okay, publish it! @kangz12345

**Comment by kangz12345** [comment]
> Please check the relaeae draft and if okay, publish it! @kangz12345

I released it, and confirmed that the pip-installation works perfectly. Nice work!
