### ISSUE TITLE
Use `logging`

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/qiwis#179]
### Feature you want to implement
Currently, the example apps and the `qiwis` system just print out the log messages to the console or broadcast them to the log channel.
However, this seems neither scalable nor modular since it does not provide any extendable interface, e.g., logging into files, log filtering, log levels, etc.
Therefore, I think we should use the Python's [`logging`](https://docs.python.org/3.7/library/logging.html) module for logging and implement a [`Handler`](https://docs.python.org/3.7/library/logging.html#logging.Handler) to send the logs to the logger app.

### How the feature is implemented
This issue will be broken into 3 sub-issues:
1. Qiwis central logging, without actually printing out anything. (When we test it, we import `qiwis` and get its logger. We will create a dedicated branch for this.) (See #180)
2. Test if the logger app can show all the logs made by `Qiwis`. (See #181)
3. Change all the apps to use `logging` to log. (See #182)

### Additional context
An image from [logging flow](https://docs.python.org/3.7/howto/logging.html#logging-flow)
![Logging flow](https://docs.python.org/3.7/_images/logging_flow.png)

**Comment by BECATRUE** [comment]
Did you intend that this issue is in the Log Viewer project?
The project  was created in the Iquip repo, but if you are okay, never mind!

**Comment by kangz12345** [comment]
> Did you intend that this issue is in the Log Viewer project?

Yes, because this is required to implement the logger in iquip!
