### ISSUE TITLE
Logger app with `logging` module

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/qiwis#181]
### Feature you want to implement
Change the logger app to show the logs generated by `logging`.

### How the feature is implemented
Nice reference: [`Logging Cookbook`](https://docs.python.org/3.7/howto/logging-cookbook.html#a-qt-gui-for-logging)

See #179 for more context.

**Comment by Aijuh** [comment]
cannot assign myself in assignees menu

**Comment by Aijuh** [comment]
Is logging library is included in logger.py by importing Baseapp from qiwis.py? Is it correct that the issue want logger.py get message from logging in qiwis.py? I am still reading reference and PyQt tutorials, so it might seem as weired question.

**Comment by kangz12345** [comment]
> Is logging library is included in logger.py by importing Baseapp from qiwis.py?

If you want to use the `logging` module in the `logger` module (logger.py), you should import `logging` again.
That is, you should do the following in logger.py:
```python
import logging
```

> Is it correct that the issue want logger.py get message from logging in qiwis.py?

Yes. Currently the `LoggerApp` listens to the "log" channel for logging, but you will change that mechanism to handle the logs directly using the `logging` module.

I think you can try the following in order:
1. Make a simple handler (you can just use these: [useful handlers](https://docs.python.org/3.7/howto/logging.html#useful-handlers)) in logger.py or any other file (you can create a new file).
2. Check if it can catch the logs from `qiwis` module (qiwis.py).
3. Referring to the [reference](https://docs.python.org/3.7/howto/logging-cookbook.html#a-qt-gui-for-logging), make the logger app to print out the log messages.

If you want to just create a new module leaving the logger.py, feel free to.
