### ISSUE TITLE
Use global constant for channel names

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/qiwis#186]
In the example codes, the channel names are hard-coded in the app codes, and it should be consistent to the ones in the "setup.json".

We can mitigate this problem by defining constants for the channel names in each app code to prevent using the string-literal channel names everywhere (in which case it is hard to rename the channels).

However, we still have to define such constants in each app code consistently. For example, assume that every app uses the logging channel. Then they have to define, e.g., `LOG_CHANNEL="log"` in each app code.

If we use the global constant which is suggested in #185, we can tackle this issue further.
However, I am not sure yet how effective this would be. For example, even if we use the global constant namespace, we still have to use the agreed constant name and any mismatch cannot be detected statically (e.g., by IDEs).

Any opinions on this?

**Comment by BECATRUE** [comment]
I also think that setting channel names as global constants is the best solution!

**Comment by BECATRUE** [comment]
@kangz12345 I realized a problem while I tested several global constants.
How can I access them in each app?

In an app class, neither `self._constants` nor `BaseApp._constants` can access them well.

I think we set the constants not in `BaseApp`, but in each app instance directly.

**Comment by kangz12345** [comment]
Referring to #189:

> For the access, `BaseApp` now provides a read-only property `constants`.

So `self.constants` should work. If you still have problems, please let me know.

**Comment by BECATRUE** [comment]
It doesn't work well. Specifically, the `constants` is an empty namespace.

**Comment by kangz12345** [comment]
Could you show me the config.json file you used? It must have `"constant"` section.

**Comment by BECATRUE** [comment]
The `config.json` for test is as follows:
```json
{
    "app": {
        "numgen": {
            "module": "examples.numgen",
            "cls": "NumGenApp",
            "show": true,
            "pos": "left",
            "channel": ["db"],
            "args": {
                "table": "number"
            }
        },
        "dbmgr": {
            "module": "examples.dbmgr",
            "cls": "DBMgrApp",
            "show": true,
            "pos": "right",
            "channel": []
        },
        "poller": {
            "module": "examples.poller",
            "cls": "PollerApp",
            "show": true,
            "pos": "bottom",
            "channel": ["db"],
            "args": {
                "table": "B"
            }
        },
        "logger": {
            "module": "examples.logger",
            "cls": "LoggerApp",
            "show": true,
            "pos": "bottom",
            "channel": []
        }
    },
    "constant": {
        "icon_path": "resources/icon.jpg",
        "background_path": "resources/background.jpg"
    }
}
```

I printed the following two properties.
- `constants_` in `main()` (qiwis.py)
```shell
ConstantNamespace(icon_path='resources/icon.jpg', background_path='resources/background.jpg')
```

- `self.constants` (numgen.py)
```shell
EmptyNamespace()
```

**Comment by BECATRUE** [comment]
I made a simple example.

### test1.py
```python
from test2 import B

class A(B):
    def show(self):
        print(self.cnt)
```

### test2.py
```python
class B:
    _cnt = 0

    @property
    def cnt(self):
        return B._cnt

def main():
    B._cnt = 1
    from test1 import A
    ins = A()
    ins.show()

if __name__ == "__main__":
    main()
```

### Result
```shell
$ python test2.py
0
```

Isn't this the same case as that we implemented?

**Comment by kangz12345** [comment]
Hmm okay interesting 😄 
I think the two `B` in `test1.py` and `test2.py` are distinct class objects, and therefore each of them has its own namespace.
In other words, `test1.B._cnt` and `test2.B._cnt` seem to be different variables.
I will make a bug issue about this. Thank you for reporting!

**Comment by BECATRUE** [comment]
After fixing the bug in #215 and implementing this issue, I plan to release the next version.
Is it okay? @kangz12345

**Comment by kangz12345** [comment]
Oh.. actually this makes a circular import, which should be avoided.
This might be a big problem than we thought.

**Comment by kangz12345** [comment]
Please continue discussion in #215 since it is out of scope of this issue.

**Comment by kangz12345** [comment]
Instead of implement it in this way, @BECATRUE and I decided to use apps' constructor arguments instead of the global constant namespace.
Constructor gives more straightforward intuition about what channel names users should provide.
