### ISSUE TITLE
Support a tab structure

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/qiwis#196]
As I work on iquip project, I thought about supporing a tab structure in qiwis.
If we open several experiment builders, the GUI looks as below.
<img width="60%" src="https://github.com/snu-quiqcl/qiwis/assets/76851886/ca296529-01fd-4a25-9573-b7a4321e1ba8">

But I think showing the builders as a tab looks more legible using [`QTabWidgeet`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QTabWidget.html).
<img width="30%" src="https://github.com/snu-quiqcl/qiwis/assets/76851886/d356e466-9df0-42a6-a35f-beb4c0d0cf72">

Feel free to leave your opinion😃

**Comment by kangz12345** [comment]
So you are suggesting to merge the builder apps using `QTabWidget`, leaving the other apps?

**Comment by kangz12345** [comment]
Oh, you created this issue in `qiwis`! I didn't know that.
So you are suggesting a new feature in `qiwis`, right?

**Comment by BECATRUE** [comment]
Yes! I just suggested a new feature of `qiwis`.

**Comment by BECATRUE** [comment]
@kangz12345 
With the issue #205, how about changing the structure into that of artiq-dashboard?

![image](https://github.com/snu-quiqcl/qiwis/assets/76851886/c7cbf448-5515-47d4-8cd7-7022cf34b699)

I want to support only the tab structure, not showing in a row.

**Comment by kangz12345** [comment]
So you want to force that each section (left, bottom, right, etc.) can has only 1 foreground widget and other frames should be stacked by the tab structure?

**Comment by BECATRUE** [comment]
> So you want to force that each section (left, bottom, right, etc.) can has only 1 foreground widget and other frames should be stacked by the tab structure?

No! In ARTIQ dashboard, all the frames are stacked in one widget in the initial state as you said, but an user can move a frame into another widget by dragging and dropping.
I want to implement like this.

**Comment by kangz12345** [comment]
Okay cool!
