### ISSUE TITLE
Support a central widget

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/qiwis#205]
Currently, we can add an app into only four positions; top, left, right, bottom.

However, I think we need a central widget, such as a builder in the artiq-dashboard.

![image](https://github.com/snu-quiqcl/qiwis/assets/76851886/24c7e048-f489-4b5c-9547-702cd3d1fb21)

Thus, the central position will be supported in this issue.

**Comment by kangz12345** [comment]
Then the _central_ widgets will initially not be docked, right?

**Comment by BECATRUE** [comment]
> Then the _central_ widgets will initially not be docked, right?

Yes, I envisioned it as you said.

**Comment by BECATRUE** [comment]
I checked the ARTIQ dashboard, and I realized that the cental widget CANNOT move into a dock widget.
Is it okay? @kangz12345

**Comment by kangz12345** [comment]
Oh really? Okay if we make a clear definition for those floating-only frame type!

**Comment by BECATRUE** [comment]
As Jiyong and I discussed, we decided to use `QMdiArea` as the central widget and each floating widget is wrapped by `QMdiSubWinow`.
