### ISSUE TITLE
Handle a frame with the initial `False` show option

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/qiwis#210]
So far, we have supported the `show` option in `config.json`.

Only if the option is `True`, frames of the app are shown.
However, in the current system, we cannot show frames with the initial `False` show option, thus, these frames have become obsolete.

Thus, we should determine how to handle this option.

**Comment by kangz12345** [comment]
Then should we add qiwiscalls for it?

**Comment by BECATRUE** [comment]
This option is not managed by each app, but relies on `config.json` and `qiwis`.
Thus it would be better to control this by adding a menu bar or something to qiwis.

However, I have not yet thought of a concrete solution.

**Comment by BECATRUE** [comment]
As @kangz12345 and I discussed, I will remove the `show` argument.
