### ISSUE TITLE
Enable the central widget, `MdiArea` scrolled

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/qiwis#221]
### Feature you want to implement
Like ARTIQ dashboard, to able to scroll the central widget, `MdiArea` looks convenient.

### How the feature is implemented
Refer to [artiq_dashboard.py](https://github.com/m-labs/artiq/blob/master/artiq/frontend/artiq_dashboard.py#L166).

**Comment by kangz12345** [comment]
We already use it, don't we? We just need to set the scroll bar policy.

**Comment by BECATRUE** [comment]
Yes! we just need to set the policy.
