### ISSUE TITLE
New initial position "floating"

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/qiwis#226]
### Feature you want to implement
Add a new initial frame position "floating", which is not docked but floating when initialized.

### How the feature is implemented
First create a dock widget and add it to the main window (docked). Then call `setFloating(True)`.

**Comment by BECATRUE** [comment]
Oh, I also planned to implement this today😃
Do you want to do it?

**Comment by kangz12345** [comment]
Oh, you can do it! I didn't start it 😄

**Comment by kangz12345** [comment]
There was a typo in #227, so a wrong PR was mentioned as to-be-closed.
Please type "#" and search for the target issue to ensure that you selected the correct issue.
@BECATRUE

**Comment by BECATRUE** [comment]
Oh, I'm sorry that I mentioned a wrong PR😥
