### ISSUE TITLE
Frame titles

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/qiwis#231]
### Feature you want to implement
For multi-frame apps, the frames have the same title, so it is hard to distinguish them when they are in tabs.
I think we should support individual frame title naming.

### How the feature is implemented
TBC

### Additional context
In `iquip`, the device monitor app has three frames and they all have the same title "monitor".

**Comment by BECATRUE** [comment]
I have also agreed with this problem, too! But, I don't know what solution is the best yet..

**Comment by BECATRUE** [comment]
As I suggested last week, how about returning the following structure in `frames()`?
```python
(("ttl monitor", self.ttlControllerFrame), ("dac monitor", self.dacControllerFrame), ...)
```

**Comment by kangz12345** [comment]
Oh, what was the reason of using `Tuple[Tuple[str, QWidget], ...]` instead of `Dict[str, QWidget]`?

**Comment by BECATRUE** [comment]
I think there may be a case where we want to use duplicated frame name.
But, if you think it is unnecessary, I will adopt your suggestion!

**Comment by kangz12345** [comment]
I see! That's reasonable.
