### ISSUE TITLE
Bothersome by the message box in qiwis-call

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/qiwis#237]
When handling a qiwis-call, it always requests confirmation by the message box, hence it is too bothering.

How about removing this procedure or checking only specified apps in config file?

**Comment by BECATRUE** [comment]
What do you think of it? @kangz12345

**Comment by kangz12345** [comment]
My idea was to add e.g. `"trust": True` in the config app info, and if an app is _trusted_, then its qiwiscall never asks for permission.

I think the default behavior must be requesting confirmation just as the current implementation, and give privilege to trusted apps.

**Comment by BECATRUE** [comment]
I see! Your idea is similar to my second idea, "checking only specified apps in config file", so let's go with this.
